controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left wheel motor"]
    right_wheel_names: ["right wheel motor"]

    wheel_separation: 0.09
    wheel_radius: 0.025

    odom_frame_id: odom
    base_frame_id: base_footprint

    enable_odom_tf: true
    position_feedback: true
    open_loop: false

    cmd_vel_timeout: 0.5
    publish_rate: 50.0

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]